# Generated by Django 3.1.1 on 2021-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchBatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimized_pair',
            name='rn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='optimized_pair',
            name='vin',
            field=models.CharField(max_length=50),
        ),
    ]
